networks:
  xrat-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    # Configuração para facilitar resolução DNS entre containers
    name: xrat-network
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"

volumes:
  mongodb_data:
  redis_data:

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: xrat-mongodb
    #estart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: xratpassword
      MONGO_INITDB_DATABASE: xrat
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/src/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      xrat-network:
        ipv4_address: 172.28.1.10

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: xrat-redis
    #restart: unless-stopped
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      xrat-network:
        ipv4_address: 172.28.1.20
    command: redis-server --appendonly yes --requirepass xratredispass
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: xrat-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:xratpassword@mongodb:27017/xrat?authSource=admin
      REDIS_URL: redis://:xratredispass@redis:6379
      JWT_SECRET: xrat-super-secret-jwt-key-change-in-production
      CORS_ORIGIN: http://localhost:5173,http://localhost:80,https://localhost,http://172.28.1.50,https://172.28.1.50
      HOST: 172.28.1.30
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      xrat-network:
        ipv4_address: 172.28.1.30

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: xrat-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: https://localhost
      VITE_WS_URL: wss://localhost/socket.io
      VITE_HOST_URL: https://localhost
      VITE_USE_MOCK_AUTH: false
      VITE_USE_MOCK_DATA: false
      VITE_USE_MOCK_WEBSOCKET: false
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      xrat-network:
        ipv4_address: 172.28.1.40

  # Nginx Reverse Proxy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: xrat-nginx
    #restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: 172.28.1.50
      BACKEND_HOST: 172.28.1.30
      FRONTEND_HOST: 172.28.1.40
    networks:
      xrat-network:
        ipv4_address: 172.28.1.50
