services:
  # MongoDB - Internal only, not exposed
  mongodb:
    image: mongo:7
    container_name: xrat-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-xrat_secret_2025}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-xrat_db}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - xrat-internal
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis - Internal only, not exposed
  redis:
    image: redis:7-alpine
    container_name: xrat-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-xrat_redis_2025}
    volumes:
      - redis_data:/data
    networks:
      - xrat-internal
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend - Exposed port
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xrat-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
      MONGODB_URI: mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-xrat_secret_2025}@mongodb:27017/${MONGO_DATABASE:-xrat_db}?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-xrat_redis_2025}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - xrat-internal
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend - Exposed port
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xrat-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    depends_on:
      - backend
    networks:
      - xrat-internal
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  xrat-internal:
    name: xrat-network
    driver: bridge
    internal: false

volumes:
  mongodb_data:
    name: xrat-mongodb-data
  mongodb_config:
    name: xrat-mongodb-config
  redis_data:
    name: xrat-redis-data
